const icons = {
  dashboardIcon: require('./dashboard.svg').default,
  desktopIcon: require('./desktop.svg').default,
  serviceIcon: require('./service.svg').default,
  numberLevelIcon: require('./numberLevel.svg').default,
  reportIcon: require('./report.svg').default,
  settingIcon: require('./setting.svg').default,
  logoutIcon: require('./logout.svg').default,
  sttDaCapIcon: require('./sttDaCap.svg').default,
  sttDaSuDungIcon: require('./sttDaSuDung.svg').default,
  sttDangChoIcon: require('./sttDangCho.svg').default,
  sttDaBoQuaIcon: require('./sttDaBoQua.svg').default,
  muiTenLenIcon: require('./muiTenLen.svg').default,
  chuongThongBaoIcon: require('./chuongThongBao.svg').default,
  circleOrangeIcon: require('./circleOrange.svg').default,
  circleBlueIcon: require('./circleBlue.svg').default,
  circleGreenIcon: require('./circleGreen.svg').default,
  dotYellowIcon: require('./dotYellow.svg').default,
  dotGrayIcon: require('./dotGray.svg').default,
};
export default icons;
