const icons = {
  // dashboardIcon: require('../../assests/icons/dashboard.svg').default,
  // desktopIcon: require('../../assests/icons/desktop.svg').default,
  // serviceIcon: require('../../assests/icons/service.svg').default,
  // numberLevelIcon: require('../../assests/icons/numberLevel.svg').default,
  // reportIcon: require('../../assests/icons/report.svg').default,
  // settingIcon: require('../../assests/icons/setting.svg').default,
  // logoutIcon: require('../../assests/icons/logout.svg').default,
  // =======
  // dashboardIcon: require("../imgs/dashboard.svg").default,
  // serviceIcon: require("../imgs/service.svg").default,
  // reportIcon: require("../imgs/report.svg").default,
  // settingIcon: require("../imgs/setting.svg").default,
  giveNumberIcon: require('../imgs/giveNumber.svg').default,
  monitorIcon: require('../imgs/monitor.svg').default,
  // logoutIcon: require("../imgs/logout.svg").default,
  downIcon: require('../imgs/down.svg').default,
  addIcon: require('../imgs/add.svg').default,
  searchIcon: require('../imgs/search.svg').default,

  dashboardIcon: require('./dashboard.svg').default,
  desktopIcon: require('./desktop.svg').default,
  serviceIcon: require('./service.svg').default,
  numberLevelIcon: require('./numberLevel.svg').default,
  reportIcon: require('./report.svg').default,
  settingIcon: require('./setting.svg').default,
  logoutIcon: require('./logout.svg').default,
  sttDaCapIcon: require('./sttDaCap.svg').default,
  sttDaSuDungIcon: require('./sttDaSuDung.svg').default,
  sttDangChoIcon: require('./sttDangCho.svg').default,
  sttDaBoQuaIcon: require('./sttDaBoQua.svg').default,
  muiTenLenIcon: require('./muiTenLen.svg').default,
  chuongThongBaoIcon: require('./chuongThongBao.svg').default,
  circleOrangeIcon: require('./circleOrange.svg').default,
  circleBlueIcon: require('./circleBlue.svg').default,
  circleGreenIcon: require('./circleGreen.svg').default,
  dotYellowIcon: require('./dotYellow.svg').default,
  dotGrayIcon: require('./dotGray.svg').default,
};
export default icons;
